Experimental
mantiuk/pwcmp pull request #1
Opened 2018-06-26 16:23 UTC by mikhailiuk

2018-06-27 17:48 UTC, mantiuk commented on pw_scale.m
> +        if strcmp(opt.prior,'gaussian')
switch / case would be nicer, also potentially faster

2018-06-27 17:52 UTC, mantiuk commented on pw_scale.m
> +comp_made = sum(sum(nnz_d));
sum(nnz_d(:))

2018-06-27 17:53 UTC, mantiuk commented on pw_scale.m
> +% [Q, R] = pw_scale( D, use_prior )
use_prior -> options

2018-06-27 17:55 UTC, mantiuk commented on pw_scale.m
>  % R - matrix of residuals. The residuals are due to projecting the
something is missing in the sentence 

"projecting to one-dimensional quality scale" - my guess

2018-06-27 17:57 UTC, mantiuk commented on pw_scale.m
> +opt.prior = '';
= 'none'

then in switch / case below - "otherwise" should generate an error
if the prior name is mistyped, the code should generate an error.

2018-06-27 17:59 UTC, mantiuk commented on pw_scale_bootstrp.m
> +% We use the prior by default
the code below does not use prior

2018-06-27 18:01 UTC, mantiuk commented on pw_scale_bootstrp.m
> +% agreeing with the number of comparisons.
I am not getting the purpose of this piece of code - we may need to check with Maria. 
We do not handle ties

2018-06-27 18:05 UTC, mantiuk requested changes
Some minor fixes needed (see comments). Check with Maria what is the purpose of the code for ties. 

Please update also "Revision history" in README.md

2018-06-28 17:24 UTC, mikhailiuk commented on pw_scale.m
>  % R - matrix of residuals. The residuals are due to projecting the
The line is complete in the code (github cut part of it)

2018-07-17 11:43 UTC, merged